name: ParkingTicketingAPI Tests

on:
  push:
   branches: [master]
  pull_request:
   branches: [master]
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     TEST_PROJECT: 'ParkingTicketingAPI.Test/ParkingTicketingAPI.Test.csproj'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore "${{ env.TEST_PROJECT }}"

      - name: Run tests
        run: dotnet test "${{ env.TEST_PROJECT }}" --no-restore --configuration Release --verbosity normal
